// Master catalog. Prices are in USD (the base storage currency).
// Floor is ~$78 (KES 10,000) for everything EXCEPT the two explicitly cheap
// items: an entry monitor and one old Android phone.

export type SeedProduct = {
  slug: string;
  name: string;
  category: string;
  brand: string;
  condition: string;
  price: number;
  originalPrice: number;
  grade: "A" | "B" | "C";
  battery: number | null;
  warrantyDays: number;
  seller: string;
  specs: string[];
  gradeNotes: string;
  image: string;
};

export const catalog: SeedProduct[] = [
  // ─────────────── PHONES ───────────────
  {
    slug: "samsung-galaxy-s24-ultra",
    name: "Samsung Galaxy S24 Ultra",
    category: "Phones",
    brand: "Samsung",
    condition: "Refurbished",
    price: 749,
    originalPrice: 1299,
    grade: "A",
    battery: 96,
    warrantyDays: 120,
    seller: "verified-reseller",
    specs: ["256GB", "Titanium Black", "S Pen", "Snapdragon 8 Gen 3"],
    gradeNotes: "Kept in a case with screen protector, immaculate.",
    image: "📱",
  },
  {
    slug: "samsung-galaxy-s23",
    name: "Samsung Galaxy S23",
    category: "Phones",
    brand: "Samsung",
    condition: "Refurbished",
    price: 429,
    originalPrice: 799,
    grade: "A",
    battery: 92,
    warrantyDays: 90,
    seller: "verified-reseller",
    specs: ["128GB", "Phantom Black", "Unlocked"],
    gradeNotes: "Light use, no marks on screen or body.",
    image: "📱",
  },
  {
    slug: "samsung-galaxy-a54",
    name: "Samsung Galaxy A54 5G",
    category: "Phones",
    brand: "Samsung",
    condition: "New",
    price: 199,
    originalPrice: 449,
    grade: "B",
    battery: 88,
    warrantyDays: 60,
    seller: "verified-reseller",
    specs: ["128GB", "Awesome Violet", "Dual SIM"],
    gradeNotes: "Minor scuffs on the frame, screen clean.",
    image: "📱",
  },
  {
    slug: "iphone-15-pro-max",
    name: "iPhone 15 Pro Max",
    category: "Phones",
    brand: "Apple",
    condition: "Refurbished",
    price: 899,
    originalPrice: 1199,
    grade: "A",
    battery: 95,
    warrantyDays: 120,
    seller: "certified-refurb",
    specs: ["256GB", "Natural Titanium", "Unlocked"],
    gradeNotes: "Open-box, activation-locked cleared, pristine.",
    image: "📱",
  },
  {
    slug: "iphone-14",
    name: "iPhone 14",
    category: "Phones",
    brand: "Apple",
    condition: "Refurbished",
    price: 449,
    originalPrice: 799,
    grade: "A",
    battery: 90,
    warrantyDays: 90,
    seller: "certified-refurb",
    specs: ["128GB", "Midnight", "Unlocked"],
    gradeNotes: "Barely a mark, battery still strong.",
    image: "📱",
  },
  {
    slug: "iphone-13-blue",
    name: "iPhone 13",
    category: "Phones",
    brand: "Apple",
    condition: "Refurbished",
    price: 349,
    originalPrice: 699,
    grade: "B",
    battery: 86,
    warrantyDays: 90,
    seller: "verified-reseller",
    specs: ["128GB", "Blue", "Unlocked"],
    gradeNotes: "Small hairline scratch on the frame, screen flawless.",
    image: "📱",
  },
  {
    slug: "iphone-se-2022",
    name: "iPhone SE (2022)",
    category: "Phones",
    brand: "Apple",
    condition: "Used",
    price: 159,
    originalPrice: 429,
    grade: "B",
    battery: 84,
    warrantyDays: 60,
    seller: "certified-refurb",
    specs: ["64GB", "Starlight", "A15 Bionic"],
    gradeNotes: "Some wear on the edges, fully functional.",
    image: "📱",
  },
  {
    slug: "google-pixel-8-pro",
    name: "Google Pixel 8 Pro",
    category: "Phones",
    brand: "Google",
    condition: "Refurbished",
    price: 499,
    originalPrice: 999,
    grade: "A",
    battery: 94,
    warrantyDays: 90,
    seller: "verified-reseller",
    specs: ["128GB", "Obsidian", "Tensor G3"],
    gradeNotes: "Screen protector on since day one, barely used.",
    image: "📱",
  },
  {
    slug: "old-android-tecno",
    name: "Tecno Spark 7 (old stock)",
    category: "Phones",
    brand: "Tecno",
    condition: "Used",
    price: 42,
    originalPrice: 130,
    grade: "C",
    battery: 72,
    warrantyDays: 30,
    seller: "budget-bin",
    specs: ["64GB", "Android 11", "Dual SIM"],
    gradeNotes: "Well used with visible wear — a cheap, working backup phone.",
    image: "📱",
  },

  // ─────────────── LAPTOPS ───────────────
  {
    slug: "macbook-pro-14-m3",
    name: "MacBook Pro 14″ M3",
    category: "Laptops",
    brand: "Apple",
    condition: "Refurbished",
    price: 1199,
    originalPrice: 1999,
    grade: "A",
    battery: 95,
    warrantyDays: 180,
    seller: "certified-refurb",
    specs: ["M3 Pro", "18GB RAM", "512GB SSD", "Space Black"],
    gradeNotes: "Corporate lease return, professionally reset.",
    image: "💻",
  },
  {
    slug: "macbook-air-m2",
    name: "MacBook Air M2",
    category: "Laptops",
    brand: "Apple",
    condition: "Refurbished",
    price: 749,
    originalPrice: 1199,
    grade: "A",
    battery: 93,
    warrantyDays: 120,
    seller: "certified-refurb",
    specs: ["M2", "8GB RAM", "256GB SSD", "Midnight"],
    gradeNotes: "Light use, no dents or scratches.",
    image: "💻",
  },
  {
    slug: "dell-xps-13",
    name: "Dell XPS 13",
    category: "Laptops",
    brand: "Dell",
    condition: "Used",
    price: 549,
    originalPrice: 1299,
    grade: "C",
    battery: 78,
    warrantyDays: 60,
    seller: "verified-reseller",
    specs: ["i7-1165G7", "16GB RAM", "512GB SSD"],
    gradeNotes: "Keyboard shine and a dented lid corner. Runs great.",
    image: "💻",
  },
  {
    slug: "lenovo-thinkpad-x1",
    name: "Lenovo ThinkPad X1 Carbon",
    category: "Laptops",
    brand: "Lenovo",
    condition: "Refurbished",
    price: 629,
    originalPrice: 1599,
    grade: "B",
    battery: 85,
    warrantyDays: 90,
    seller: "certified-refurb",
    specs: ["i7-1260P", "16GB RAM", "1TB SSD"],
    gradeNotes: "Typical business wear, screen spotless.",
    image: "💻",
  },
  {
    slug: "hp-pavilion-15",
    name: "HP Pavilion 15",
    category: "Laptops",
    brand: "HP",
    condition: "Refurbished",
    price: 329,
    originalPrice: 749,
    grade: "B",
    battery: 82,
    warrantyDays: 60,
    seller: "verified-reseller",
    specs: ["Ryzen 5", "8GB RAM", "512GB SSD"],
    gradeNotes: "A few scuffs on the lid, works perfectly.",
    image: "💻",
  },

  // ─────────────── TVS ───────────────
  {
    slug: "lg-c3-55-oled",
    name: "LG C3 55″ OLED",
    category: "TVs",
    brand: "LG",
    condition: "Refurbished",
    price: 799,
    originalPrice: 1499,
    grade: "A",
    battery: null,
    warrantyDays: 120,
    seller: "screen-source",
    specs: ["55-inch", "4K OLED", "120Hz", "webOS"],
    gradeNotes: "No dead pixels, panel tested. Original stand and remote.",
    image: "📺",
  },
  {
    slug: "samsung-qled-50",
    name: "Samsung 50″ QLED 4K",
    category: "TVs",
    brand: "Samsung",
    condition: "Refurbished",
    price: 429,
    originalPrice: 899,
    grade: "B",
    battery: null,
    warrantyDays: 90,
    seller: "screen-source",
    specs: ["50-inch", "4K QLED", "Tizen", "HDR10+"],
    gradeNotes: "Slight scuff on the bezel, screen flawless.",
    image: "📺",
  },
  {
    slug: "sony-bravia-43",
    name: "Sony Bravia 43″ LED",
    category: "TVs",
    brand: "Sony",
    condition: "Refurbished",
    price: 289,
    originalPrice: 649,
    grade: "B",
    battery: null,
    warrantyDays: 90,
    seller: "screen-source",
    specs: ["43-inch", "4K LED", "Google TV"],
    gradeNotes: "Stand shows light wear, picture is crisp.",
    image: "📺",
  },

  // ─────────────── SOUND SYSTEMS ───────────────
  {
    slug: "sonos-arc",
    name: "Sonos Arc Soundbar",
    category: "Sound Systems",
    brand: "Sonos",
    condition: "Refurbished",
    price: 549,
    originalPrice: 899,
    grade: "A",
    battery: null,
    warrantyDays: 90,
    seller: "audio-outpost",
    specs: ["Dolby Atmos", "Wi-Fi", "AirPlay 2"],
    gradeNotes: "Boxed with all cables, barely used.",
    image: "🔊",
  },
  {
    slug: "jbl-partybox-310",
    name: "JBL PartyBox 310",
    category: "Sound Systems",
    brand: "JBL",
    condition: "Refurbished",
    price: 299,
    originalPrice: 549,
    grade: "B",
    battery: 90,
    warrantyDays: 60,
    seller: "audio-outpost",
    specs: ["Bluetooth", "240W", "Light show", "Wheels"],
    gradeNotes: "Scuffs from transport, sounds huge.",
    image: "🔊",
  },
  {
    slug: "bose-soundlink-revolve",
    name: "Bose SoundLink Revolve+",
    category: "Sound Systems",
    brand: "Bose",
    condition: "Refurbished",
    price: 129,
    originalPrice: 299,
    grade: "A",
    battery: 91,
    warrantyDays: 60,
    seller: "audio-outpost",
    specs: ["360° sound", "Bluetooth", "17hr battery"],
    gradeNotes: "Clean, still holds a full charge.",
    image: "🔊",
  },

  // ─────────────── FRIDGES ───────────────
  {
    slug: "lg-double-door-fridge",
    name: "LG Double-Door Fridge 260L",
    category: "Fridges",
    brand: "LG",
    condition: "Refurbished",
    price: 389,
    originalPrice: 749,
    grade: "B",
    battery: null,
    warrantyDays: 120,
    seller: "home-appliance-hub",
    specs: ["260 litres", "Frost-free", "Inverter compressor"],
    gradeNotes: "Minor scratches on the side, cools perfectly.",
    image: "🧊",
  },
  {
    slug: "samsung-bespoke-fridge",
    name: "Samsung Bespoke Fridge 320L",
    category: "Fridges",
    brand: "Samsung",
    condition: "Refurbished",
    price: 599,
    originalPrice: 1099,
    grade: "A",
    battery: null,
    warrantyDays: 150,
    seller: "home-appliance-hub",
    specs: ["320 litres", "Digital inverter", "Water dispenser"],
    gradeNotes: "Showroom unit, spotless inside and out.",
    image: "🧊",
  },
  {
    slug: "hisense-bar-fridge",
    name: "Hisense Bar Fridge 90L",
    category: "Fridges",
    brand: "Hisense",
    condition: "Refurbished",
    price: 129,
    originalPrice: 249,
    grade: "B",
    battery: null,
    warrantyDays: 90,
    seller: "home-appliance-hub",
    specs: ["90 litres", "Compact", "Reversible door"],
    gradeNotes: "Small dent on the door, runs quiet and cold.",
    image: "🧊",
  },

  // ─────────────── TABLETS ───────────────
  {
    slug: "ipad-air-5",
    name: "iPad Air (5th gen)",
    category: "Tablets",
    brand: "Apple",
    condition: "Refurbished",
    price: 349,
    originalPrice: 599,
    grade: "A",
    battery: 97,
    warrantyDays: 90,
    seller: "certified-refurb",
    specs: ["64GB", "Wi-Fi", "Starlight", "M1 chip"],
    gradeNotes: "Open-box return, film still on the back.",
    image: "📱",
  },
  {
    slug: "samsung-tab-s9",
    name: "Samsung Galaxy Tab S9",
    category: "Tablets",
    brand: "Samsung",
    condition: "Refurbished",
    price: 449,
    originalPrice: 799,
    grade: "A",
    battery: 94,
    warrantyDays: 90,
    seller: "verified-reseller",
    specs: ["128GB", "S Pen included", "AMOLED"],
    gradeNotes: "Pristine, with S Pen and box.",
    image: "📱",
  },

  // ─────────────── CAMERAS ───────────────
  {
    slug: "sony-a7iii",
    name: "Sony A7 III",
    category: "Cameras",
    brand: "Sony",
    condition: "Refurbished",
    price: 1099,
    originalPrice: 1999,
    grade: "B",
    battery: null,
    warrantyDays: 60,
    seller: "camera-collective",
    specs: ["24.2MP", "12,400 shutter count", "Body only"],
    gradeNotes: "Grip shows light brassing. Sensor clean, shutter tested.",
    image: "📷",
  },
  {
    slug: "canon-r6",
    name: "Canon EOS R6",
    category: "Cameras",
    brand: "Canon",
    condition: "Refurbished",
    price: 1349,
    originalPrice: 2499,
    grade: "A",
    battery: null,
    warrantyDays: 90,
    seller: "camera-collective",
    specs: ["20.1MP", "8,900 shutter count", "Body only"],
    gradeNotes: "Studio unit, kept in a case between shoots.",
    image: "📷",
  },

  // ─────────────── GAMING ───────────────
  {
    slug: "playstation-5",
    name: "PlayStation 5 (Disc)",
    category: "Gaming",
    brand: "Sony",
    condition: "Refurbished",
    price: 379,
    originalPrice: 549,
    grade: "A",
    battery: null,
    warrantyDays: 90,
    seller: "game-exchange",
    specs: ["825GB SSD", "1 DualSense", "Disc edition"],
    gradeNotes: "Adult-owned, low hours, boxed.",
    image: "🎮",
  },
  {
    slug: "nintendo-switch-oled",
    name: "Nintendo Switch OLED",
    category: "Gaming",
    brand: "Nintendo",
    condition: "Refurbished",
    price: 199,
    originalPrice: 349,
    grade: "B",
    battery: null,
    warrantyDays: 60,
    seller: "game-exchange",
    specs: ["White dock", "64GB", "Joy-Cons tested for drift"],
    gradeNotes: "A few scratches on the dock, screen clean.",
    image: "🎮",
  },
  {
    slug: "xbox-series-s",
    name: "Xbox Series S",
    category: "Gaming",
    brand: "Microsoft",
    condition: "Refurbished",
    price: 179,
    originalPrice: 299,
    grade: "B",
    battery: null,
    warrantyDays: 60,
    seller: "game-exchange",
    specs: ["512GB SSD", "1 controller", "All-digital"],
    gradeNotes: "Light dust marks, fully working.",
    image: "🎮",
  },

  // ─────────────── MONITORS ───────────────
  {
    slug: "dell-24-monitor",
    name: "Dell 24″ Monitor (entry)",
    category: "Monitors",
    brand: "Dell",
    condition: "Used",
    price: 59,
    originalPrice: 149,
    grade: "C",
    battery: null,
    warrantyDays: 30,
    seller: "budget-bin",
    specs: ["24-inch", "1080p", "IPS", "HDMI + VGA"],
    gradeNotes: "Visible wear on the stand, panel has no dead pixels.",
    image: "🖥️",
  },
  {
    slug: "lg-ultragear-27",
    name: "LG UltraGear 27″ 144Hz",
    category: "Monitors",
    brand: "LG",
    condition: "Refurbished",
    price: 189,
    originalPrice: 379,
    grade: "A",
    battery: null,
    warrantyDays: 90,
    seller: "screen-source",
    specs: ["27-inch", "1440p", "144Hz", "1ms"],
    gradeNotes: "Gaming monitor in great shape, boxed.",
    image: "🖥️",
  },

  // ─────────────── MORE PHONES ───────────────
  {
    slug: "iphone-15",
    name: "iPhone 15",
    category: "Phones",
    brand: "Apple",
    condition: "Refurbished",
    price: 619,
    originalPrice: 899,
    grade: "A",
    battery: 94,
    warrantyDays: 120,
    seller: "certified-refurb",
    specs: ["128GB", "Pink", "USB-C", "Unlocked"],
    gradeNotes: "Excellent condition, minimal use.",
    image: "📱",
  },
  {
    slug: "iphone-14-pro",
    name: "iPhone 14 Pro",
    category: "Phones",
    brand: "Apple",
    condition: "Refurbished",
    price: 649,
    originalPrice: 999,
    grade: "A",
    battery: 91,
    warrantyDays: 120,
    seller: "certified-refurb",
    specs: ["256GB", "Deep Purple", "Dynamic Island", "Unlocked"],
    gradeNotes: "Clean, screen protector fitted from new.",
    image: "📱",
  },
  {
    slug: "iphone-12",
    name: "iPhone 12",
    category: "Phones",
    brand: "Apple",
    condition: "Refurbished",
    price: 259,
    originalPrice: 699,
    grade: "B",
    battery: 84,
    warrantyDays: 90,
    seller: "verified-reseller",
    specs: ["128GB", "Black", "Unlocked"],
    gradeNotes: "Light wear on the frame, screen clean.",
    image: "📱",
  },
  {
    slug: "iphone-11",
    name: "iPhone 11",
    category: "Phones",
    brand: "Apple",
    condition: "Refurbished",
    price: 189,
    originalPrice: 599,
    grade: "B",
    battery: 82,
    warrantyDays: 90,
    seller: "verified-reseller",
    specs: ["64GB", "White", "Unlocked"],
    gradeNotes: "Popular workhorse, some edge scuffs.",
    image: "📱",
  },
  {
    slug: "iphone-11-pro-max",
    name: "iPhone 11 Pro Max",
    category: "Phones",
    brand: "Apple",
    condition: "Refurbished",
    price: 239,
    originalPrice: 799,
    grade: "B",
    battery: 83,
    warrantyDays: 90,
    seller: "certified-refurb",
    specs: ["64GB", "Midnight Green", "Unlocked"],
    gradeNotes: "Great battery for its age, minor marks.",
    image: "📱",
  },
  {
    slug: "samsung-galaxy-s24",
    name: "Samsung Galaxy S24",
    category: "Phones",
    brand: "Samsung",
    condition: "Refurbished",
    price: 549,
    originalPrice: 899,
    grade: "A",
    battery: 95,
    warrantyDays: 120,
    seller: "verified-reseller",
    specs: ["256GB", "Onyx Black", "Snapdragon 8 Gen 3"],
    gradeNotes: "Immaculate, kept in a folio case.",
    image: "📱",
  },
  {
    slug: "samsung-galaxy-s22-ultra",
    name: "Samsung Galaxy S22 Ultra",
    category: "Phones",
    brand: "Samsung",
    condition: "Refurbished",
    price: 399,
    originalPrice: 1199,
    grade: "B",
    battery: 87,
    warrantyDays: 90,
    seller: "verified-reseller",
    specs: ["256GB", "Burgundy", "S Pen", "Unlocked"],
    gradeNotes: "Light scuffs, S Pen works perfectly.",
    image: "📱",
  },
  {
    slug: "samsung-galaxy-s22",
    name: "Samsung Galaxy S22",
    category: "Phones",
    brand: "Samsung",
    condition: "Refurbished",
    price: 289,
    originalPrice: 799,
    grade: "B",
    battery: 85,
    warrantyDays: 90,
    seller: "verified-reseller",
    specs: ["128GB", "Green", "Unlocked"],
    gradeNotes: "Solid daily phone, minor wear.",
    image: "📱",
  },
  {
    slug: "samsung-galaxy-a35",
    name: "Samsung Galaxy A35 5G",
    category: "Phones",
    brand: "Samsung",
    condition: "New",
    price: 179,
    originalPrice: 399,
    grade: "A",
    battery: 93,
    warrantyDays: 60,
    seller: "verified-reseller",
    specs: ["128GB", "Awesome Navy", "Dual SIM"],
    gradeNotes: "Barely used, like new.",
    image: "📱",
  },
  {
    slug: "google-pixel-8",
    name: "Google Pixel 8",
    category: "Phones",
    brand: "Google",
    condition: "Refurbished",
    price: 339,
    originalPrice: 699,
    grade: "A",
    battery: 93,
    warrantyDays: 90,
    seller: "certified-refurb",
    specs: ["128GB", "Hazel", "Tensor G3"],
    gradeNotes: "Refurbished to like-new, clean.",
    image: "📱",
  },
  {
    slug: "google-pixel-7-pro",
    name: "Google Pixel 7 Pro",
    category: "Phones",
    brand: "Google",
    condition: "Refurbished",
    price: 329,
    originalPrice: 899,
    grade: "B",
    battery: 88,
    warrantyDays: 90,
    seller: "verified-reseller",
    specs: ["128GB", "Obsidian", "Tensor G2"],
    gradeNotes: "Minor marks, superb camera.",
    image: "📱",
  },
  {
    slug: "google-pixel-7",
    name: "Google Pixel 7",
    category: "Phones",
    brand: "Google",
    condition: "Refurbished",
    price: 219,
    originalPrice: 599,
    grade: "B",
    battery: 86,
    warrantyDays: 90,
    seller: "verified-reseller",
    specs: ["128GB", "Snow", "Tensor G2"],
    gradeNotes: "Clean, light use.",
    image: "📱",
  },
  {
    slug: "google-pixel-7a",
    name: "Google Pixel 7a",
    category: "Phones",
    brand: "Google",
    condition: "New",
    price: 179,
    originalPrice: 499,
    grade: "A",
    battery: 92,
    warrantyDays: 90,
    seller: "certified-refurb",
    specs: ["128GB", "Charcoal", "90Hz OLED"],
    gradeNotes: "Excellent value, near new.",
    image: "📱",
  },
  {
    slug: "google-pixel-6",
    name: "Google Pixel 6",
    category: "Phones",
    brand: "Google",
    condition: "Used",
    price: 149,
    originalPrice: 599,
    grade: "B",
    battery: 84,
    warrantyDays: 60,
    seller: "verified-reseller",
    specs: ["128GB", "Stormy Black", "Tensor"],
    gradeNotes: "Well-priced, some visible wear.",
    image: "📱",
  },

  // ─────────────── MORE LAPTOPS ───────────────
  {
    slug: "macbook-pro-16-m1",
    name: "MacBook Pro 16″ M1 Pro",
    category: "Laptops",
    brand: "Apple",
    condition: "Refurbished",
    price: 1099,
    originalPrice: 2499,
    grade: "B",
    battery: 88,
    warrantyDays: 120,
    seller: "certified-refurb",
    specs: ["M1 Pro", "16GB RAM", "512GB SSD", "Space Gray"],
    gradeNotes: "Light wear on the lid, screen flawless.",
    image: "💻",
  },
  {
    slug: "macbook-air-m1",
    name: "MacBook Air M1",
    category: "Laptops",
    brand: "Apple",
    condition: "Refurbished",
    price: 549,
    originalPrice: 999,
    grade: "B",
    battery: 87,
    warrantyDays: 90,
    seller: "certified-refurb",
    specs: ["M1", "8GB RAM", "256GB SSD", "Silver"],
    gradeNotes: "Popular pick, minor scuffs.",
    image: "💻",
  },
  {
    slug: "hp-elitebook-840",
    name: "HP EliteBook 840 G8",
    category: "Laptops",
    brand: "HP",
    condition: "Refurbished",
    price: 429,
    originalPrice: 1199,
    grade: "B",
    battery: 84,
    warrantyDays: 90,
    seller: "certified-refurb",
    specs: ["i5-1135G7", "16GB RAM", "512GB SSD"],
    gradeNotes: "Ex-corporate, typical light wear.",
    image: "💻",
  },
  {
    slug: "lenovo-ideapad-5",
    name: "Lenovo IdeaPad 5",
    category: "Laptops",
    brand: "Lenovo",
    condition: "Refurbished",
    price: 299,
    originalPrice: 749,
    grade: "B",
    battery: 82,
    warrantyDays: 60,
    seller: "verified-reseller",
    specs: ["Ryzen 5", "8GB RAM", "512GB SSD"],
    gradeNotes: "Good student laptop, some wear.",
    image: "💻",
  },
  {
    slug: "dell-latitude-7420",
    name: "Dell Latitude 7420",
    category: "Laptops",
    brand: "Dell",
    condition: "Refurbished",
    price: 389,
    originalPrice: 1099,
    grade: "B",
    battery: 83,
    warrantyDays: 90,
    seller: "certified-refurb",
    specs: ["i7-1165G7", "16GB RAM", "256GB SSD"],
    gradeNotes: "Business-grade, reliable, light marks.",
    image: "💻",
  },

  // ─────────────── MORE TVS ───────────────
  {
    slug: "samsung-65-crystal-uhd",
    name: "Samsung 65″ Crystal UHD",
    category: "TVs",
    brand: "Samsung",
    condition: "Refurbished",
    price: 549,
    originalPrice: 999,
    grade: "B",
    battery: null,
    warrantyDays: 90,
    seller: "screen-source",
    specs: ["65-inch", "4K UHD", "Tizen", "HDR"],
    gradeNotes: "Slight bezel scuff, superb picture.",
    image: "📺",
  },
  {
    slug: "lg-oled-48-c2",
    name: "LG C2 48″ OLED",
    category: "TVs",
    brand: "LG",
    condition: "Refurbished",
    price: 649,
    originalPrice: 1299,
    grade: "A",
    battery: null,
    warrantyDays: 120,
    seller: "screen-source",
    specs: ["48-inch", "4K OLED", "120Hz", "webOS"],
    gradeNotes: "No burn-in, panel tested and perfect.",
    image: "📺",
  },
  {
    slug: "tcl-55-4k",
    name: "TCL 55″ 4K Smart TV",
    category: "TVs",
    brand: "TCL",
    condition: "Refurbished",
    price: 269,
    originalPrice: 549,
    grade: "B",
    battery: null,
    warrantyDays: 90,
    seller: "screen-source",
    specs: ["55-inch", "4K", "Google TV", "HDR10"],
    gradeNotes: "Stand shows wear, screen clean.",
    image: "📺",
  },

  // ─────────────── MORE AUDIO ───────────────
  {
    slug: "sonos-beam-gen2",
    name: "Sonos Beam (Gen 2)",
    category: "Sound Systems",
    brand: "Sonos",
    condition: "Refurbished",
    price: 279,
    originalPrice: 499,
    grade: "A",
    battery: null,
    warrantyDays: 90,
    seller: "audio-outpost",
    specs: ["Dolby Atmos", "Wi-Fi", "HDMI eARC"],
    gradeNotes: "Boxed, barely used.",
    image: "🔊",
  },
  {
    slug: "jbl-charge-5",
    name: "JBL Charge 5",
    category: "Sound Systems",
    brand: "JBL",
    condition: "Refurbished",
    price: 99,
    originalPrice: 199,
    grade: "B",
    battery: 90,
    warrantyDays: 60,
    seller: "audio-outpost",
    specs: ["Bluetooth", "IP67", "20hr battery", "Powerbank"],
    gradeNotes: "Some scuffs, sounds great, holds charge.",
    image: "🔊",
  },
  {
    slug: "bose-qc-earbuds-ii",
    name: "Bose QuietComfort Earbuds II",
    category: "Sound Systems",
    brand: "Bose",
    condition: "Refurbished",
    price: 129,
    originalPrice: 299,
    grade: "A",
    battery: 90,
    warrantyDays: 60,
    seller: "audio-outpost",
    specs: ["ANC", "Bluetooth 5.3", "With case"],
    gradeNotes: "Clean, ear tips replaced with new.",
    image: "🔊",
  },

  // ─────────────── MORE FRIDGES ───────────────
  {
    slug: "hisense-double-door-350",
    name: "Hisense Double-Door Fridge 350L",
    category: "Fridges",
    brand: "Hisense",
    condition: "Refurbished",
    price: 429,
    originalPrice: 799,
    grade: "B",
    battery: null,
    warrantyDays: 120,
    seller: "home-appliance-hub",
    specs: ["350 litres", "Frost-free", "Inverter"],
    gradeNotes: "Minor scratches on the side, cools well.",
    image: "🧊",
  },
  {
    slug: "lg-instaview-fridge",
    name: "LG InstaView Fridge 420L",
    category: "Fridges",
    brand: "LG",
    condition: "Refurbished",
    price: 749,
    originalPrice: 1499,
    grade: "A",
    battery: null,
    warrantyDays: 150,
    seller: "home-appliance-hub",
    specs: ["420 litres", "Door-in-door", "Water/ice dispenser"],
    gradeNotes: "Showroom model, spotless.",
    image: "🧊",
  },

  // ─────────────── MORE TABLETS ───────────────
  {
    slug: "ipad-pro-11-m2",
    name: "iPad Pro 11″ M2",
    category: "Tablets",
    brand: "Apple",
    condition: "Refurbished",
    price: 599,
    originalPrice: 999,
    grade: "A",
    battery: 95,
    warrantyDays: 120,
    seller: "certified-refurb",
    specs: ["128GB", "Wi-Fi", "Space Gray", "M2 chip"],
    gradeNotes: "Pristine, with box.",
    image: "📱",
  },
  {
    slug: "ipad-10th-gen",
    name: "iPad (10th gen)",
    category: "Tablets",
    brand: "Apple",
    condition: "New",
    price: 279,
    originalPrice: 449,
    grade: "A",
    battery: 94,
    warrantyDays: 90,
    seller: "certified-refurb",
    specs: ["64GB", "Wi-Fi", "Blue"],
    gradeNotes: "Light use, excellent condition.",
    image: "📱",
  },
  {
    slug: "samsung-tab-a9-plus",
    name: "Samsung Galaxy Tab A9+",
    category: "Tablets",
    brand: "Samsung",
    condition: "New",
    price: 149,
    originalPrice: 269,
    grade: "B",
    battery: 90,
    warrantyDays: 60,
    seller: "verified-reseller",
    specs: ["64GB", "Wi-Fi", "Graphite"],
    gradeNotes: "Good budget tablet, minor wear.",
    image: "📱",
  },

  // ─────────────── MORE CAMERAS ───────────────
  {
    slug: "sony-zv-e10",
    name: "Sony ZV-E10",
    category: "Cameras",
    brand: "Sony",
    condition: "Refurbished",
    price: 499,
    originalPrice: 799,
    grade: "A",
    battery: null,
    warrantyDays: 90,
    seller: "camera-collective",
    specs: ["24.2MP", "Vlogging", "With 16-50mm lens"],
    gradeNotes: "Creator favourite, low shutter count.",
    image: "📷",
  },
  {
    slug: "fujifilm-xt30",
    name: "Fujifilm X-T30 II",
    category: "Cameras",
    brand: "Fujifilm",
    condition: "Refurbished",
    price: 649,
    originalPrice: 999,
    grade: "B",
    battery: null,
    warrantyDays: 60,
    seller: "camera-collective",
    specs: ["26.1MP", "Body only", "APS-C"],
    gradeNotes: "Light brassing on edges, sensor clean.",
    image: "📷",
  },

  // ─────────────── MORE GAMING ───────────────
  {
    slug: "playstation-5-slim",
    name: "PlayStation 5 Slim",
    category: "Gaming",
    brand: "Sony",
    condition: "Refurbished",
    price: 399,
    originalPrice: 549,
    grade: "A",
    battery: null,
    warrantyDays: 90,
    seller: "game-exchange",
    specs: ["1TB SSD", "1 DualSense", "Disc edition"],
    gradeNotes: "Barely used, boxed with extras.",
    image: "🎮",
  },
  {
    slug: "xbox-series-x",
    name: "Xbox Series X",
    category: "Gaming",
    brand: "Microsoft",
    condition: "Refurbished",
    price: 349,
    originalPrice: 499,
    grade: "B",
    battery: null,
    warrantyDays: 90,
    seller: "game-exchange",
    specs: ["1TB SSD", "1 controller", "4K"],
    gradeNotes: "Light dust marks, fully working.",
    image: "🎮",
  },
  {
    slug: "steam-deck-oled",
    name: "Steam Deck OLED",
    category: "Gaming",
    brand: "Valve",
    condition: "Refurbished",
    price: 429,
    originalPrice: 649,
    grade: "A",
    battery: 96,
    warrantyDays: 90,
    seller: "game-exchange",
    specs: ["512GB", "OLED screen", "With case"],
    gradeNotes: "Excellent condition, boxed.",
    image: "🎮",
  },
  {
    slug: "nintendo-switch-lite",
    name: "Nintendo Switch Lite",
    category: "Gaming",
    brand: "Nintendo",
    condition: "Refurbished",
    price: 119,
    originalPrice: 199,
    grade: "B",
    battery: null,
    warrantyDays: 60,
    seller: "game-exchange",
    specs: ["Turquoise", "32GB", "Handheld only"],
    gradeNotes: "Some scratches, screen clean.",
    image: "🎮",
  },

  // ─────────────── MORE MONITORS ───────────────
  {
    slug: "dell-ultrasharp-27-4k",
    name: "Dell UltraSharp 27″ 4K",
    category: "Monitors",
    brand: "Dell",
    condition: "Refurbished",
    price: 279,
    originalPrice: 579,
    grade: "A",
    battery: null,
    warrantyDays: 90,
    seller: "screen-source",
    specs: ["27-inch", "4K", "IPS", "USB-C hub"],
    gradeNotes: "Professional panel, no dead pixels.",
    image: "🖥️",
  },
  {
    slug: "samsung-odyssey-g5-32",
    name: "Samsung Odyssey G5 32″",
    category: "Monitors",
    brand: "Samsung",
    condition: "Refurbished",
    price: 219,
    originalPrice: 449,
    grade: "B",
    battery: null,
    warrantyDays: 90,
    seller: "screen-source",
    specs: ["32-inch", "1440p", "144Hz", "Curved"],
    gradeNotes: "Stand has wear, panel great.",
    image: "🖥️",
  },
];
