// Master catalog. Prices are in USD (the base storage currency).
// Floor is ~$78 (KES 10,000) for everything EXCEPT the two explicitly cheap
// items: an entry monitor and one old Android phone.

export type SeedProduct = {
  slug: string;
  name: string;
  category: string;
  price: number;
  originalPrice: number;
  grade: "A" | "B" | "C";
  battery: number | null;
  warrantyDays: number;
  seller: string;
  specs: string[];
  gradeNotes: string;
  image: string;
};

export const catalog: SeedProduct[] = [
  // ─────────────── PHONES ───────────────
  {
    slug: "samsung-galaxy-s24-ultra",
    name: "Samsung Galaxy S24 Ultra",
    category: "Phones",
    price: 749,
    originalPrice: 1299,
    grade: "A",
    battery: 96,
    warrantyDays: 120,
    seller: "verified-reseller",
    specs: ["256GB", "Titanium Black", "S Pen", "Snapdragon 8 Gen 3"],
    gradeNotes: "Kept in a case with screen protector, immaculate.",
    image: "📱",
  },
  {
    slug: "samsung-galaxy-s23",
    name: "Samsung Galaxy S23",
    category: "Phones",
    price: 429,
    originalPrice: 799,
    grade: "A",
    battery: 92,
    warrantyDays: 90,
    seller: "verified-reseller",
    specs: ["128GB", "Phantom Black", "Unlocked"],
    gradeNotes: "Light use, no marks on screen or body.",
    image: "📱",
  },
  {
    slug: "samsung-galaxy-a54",
    name: "Samsung Galaxy A54 5G",
    category: "Phones",
    price: 199,
    originalPrice: 449,
    grade: "B",
    battery: 88,
    warrantyDays: 60,
    seller: "verified-reseller",
    specs: ["128GB", "Awesome Violet", "Dual SIM"],
    gradeNotes: "Minor scuffs on the frame, screen clean.",
    image: "📱",
  },
  {
    slug: "iphone-15-pro-max",
    name: "iPhone 15 Pro Max",
    category: "Phones",
    price: 899,
    originalPrice: 1199,
    grade: "A",
    battery: 95,
    warrantyDays: 120,
    seller: "certified-refurb",
    specs: ["256GB", "Natural Titanium", "Unlocked"],
    gradeNotes: "Open-box, activation-locked cleared, pristine.",
    image: "📱",
  },
  {
    slug: "iphone-14",
    name: "iPhone 14",
    category: "Phones",
    price: 449,
    originalPrice: 799,
    grade: "A",
    battery: 90,
    warrantyDays: 90,
    seller: "certified-refurb",
    specs: ["128GB", "Midnight", "Unlocked"],
    gradeNotes: "Barely a mark, battery still strong.",
    image: "📱",
  },
  {
    slug: "iphone-13-blue",
    name: "iPhone 13",
    category: "Phones",
    price: 349,
    originalPrice: 699,
    grade: "B",
    battery: 86,
    warrantyDays: 90,
    seller: "verified-reseller",
    specs: ["128GB", "Blue", "Unlocked"],
    gradeNotes: "Small hairline scratch on the frame, screen flawless.",
    image: "📱",
  },
  {
    slug: "iphone-se-2022",
    name: "iPhone SE (2022)",
    category: "Phones",
    price: 159,
    originalPrice: 429,
    grade: "B",
    battery: 84,
    warrantyDays: 60,
    seller: "certified-refurb",
    specs: ["64GB", "Starlight", "A15 Bionic"],
    gradeNotes: "Some wear on the edges, fully functional.",
    image: "📱",
  },
  {
    slug: "google-pixel-8-pro",
    name: "Google Pixel 8 Pro",
    category: "Phones",
    price: 499,
    originalPrice: 999,
    grade: "A",
    battery: 94,
    warrantyDays: 90,
    seller: "verified-reseller",
    specs: ["128GB", "Obsidian", "Tensor G3"],
    gradeNotes: "Screen protector on since day one, barely used.",
    image: "📱",
  },
  {
    slug: "old-android-tecno",
    name: "Tecno Spark 7 (old stock)",
    category: "Phones",
    price: 42,
    originalPrice: 130,
    grade: "C",
    battery: 72,
    warrantyDays: 30,
    seller: "budget-bin",
    specs: ["64GB", "Android 11", "Dual SIM"],
    gradeNotes: "Well used with visible wear — a cheap, working backup phone.",
    image: "📱",
  },

  // ─────────────── LAPTOPS ───────────────
  {
    slug: "macbook-pro-14-m3",
    name: "MacBook Pro 14″ M3",
    category: "Laptops",
    price: 1199,
    originalPrice: 1999,
    grade: "A",
    battery: 95,
    warrantyDays: 180,
    seller: "certified-refurb",
    specs: ["M3 Pro", "18GB RAM", "512GB SSD", "Space Black"],
    gradeNotes: "Corporate lease return, professionally reset.",
    image: "💻",
  },
  {
    slug: "macbook-air-m2",
    name: "MacBook Air M2",
    category: "Laptops",
    price: 749,
    originalPrice: 1199,
    grade: "A",
    battery: 93,
    warrantyDays: 120,
    seller: "certified-refurb",
    specs: ["M2", "8GB RAM", "256GB SSD", "Midnight"],
    gradeNotes: "Light use, no dents or scratches.",
    image: "💻",
  },
  {
    slug: "dell-xps-13",
    name: "Dell XPS 13",
    category: "Laptops",
    price: 549,
    originalPrice: 1299,
    grade: "C",
    battery: 78,
    warrantyDays: 60,
    seller: "verified-reseller",
    specs: ["i7-1165G7", "16GB RAM", "512GB SSD"],
    gradeNotes: "Keyboard shine and a dented lid corner. Runs great.",
    image: "💻",
  },
  {
    slug: "lenovo-thinkpad-x1",
    name: "Lenovo ThinkPad X1 Carbon",
    category: "Laptops",
    price: 629,
    originalPrice: 1599,
    grade: "B",
    battery: 85,
    warrantyDays: 90,
    seller: "certified-refurb",
    specs: ["i7-1260P", "16GB RAM", "1TB SSD"],
    gradeNotes: "Typical business wear, screen spotless.",
    image: "💻",
  },
  {
    slug: "hp-pavilion-15",
    name: "HP Pavilion 15",
    category: "Laptops",
    price: 329,
    originalPrice: 749,
    grade: "B",
    battery: 82,
    warrantyDays: 60,
    seller: "verified-reseller",
    specs: ["Ryzen 5", "8GB RAM", "512GB SSD"],
    gradeNotes: "A few scuffs on the lid, works perfectly.",
    image: "💻",
  },

  // ─────────────── TVS ───────────────
  {
    slug: "lg-c3-55-oled",
    name: "LG C3 55″ OLED",
    category: "TVs",
    price: 799,
    originalPrice: 1499,
    grade: "A",
    battery: null,
    warrantyDays: 120,
    seller: "screen-source",
    specs: ["55-inch", "4K OLED", "120Hz", "webOS"],
    gradeNotes: "No dead pixels, panel tested. Original stand and remote.",
    image: "📺",
  },
  {
    slug: "samsung-qled-50",
    name: "Samsung 50″ QLED 4K",
    category: "TVs",
    price: 429,
    originalPrice: 899,
    grade: "B",
    battery: null,
    warrantyDays: 90,
    seller: "screen-source",
    specs: ["50-inch", "4K QLED", "Tizen", "HDR10+"],
    gradeNotes: "Slight scuff on the bezel, screen flawless.",
    image: "📺",
  },
  {
    slug: "sony-bravia-43",
    name: "Sony Bravia 43″ LED",
    category: "TVs",
    price: 289,
    originalPrice: 649,
    grade: "B",
    battery: null,
    warrantyDays: 90,
    seller: "screen-source",
    specs: ["43-inch", "4K LED", "Google TV"],
    gradeNotes: "Stand shows light wear, picture is crisp.",
    image: "📺",
  },

  // ─────────────── SOUND SYSTEMS ───────────────
  {
    slug: "sonos-arc",
    name: "Sonos Arc Soundbar",
    category: "Sound Systems",
    price: 549,
    originalPrice: 899,
    grade: "A",
    battery: null,
    warrantyDays: 90,
    seller: "audio-outpost",
    specs: ["Dolby Atmos", "Wi-Fi", "AirPlay 2"],
    gradeNotes: "Boxed with all cables, barely used.",
    image: "🔊",
  },
  {
    slug: "jbl-partybox-310",
    name: "JBL PartyBox 310",
    category: "Sound Systems",
    price: 299,
    originalPrice: 549,
    grade: "B",
    battery: 90,
    warrantyDays: 60,
    seller: "audio-outpost",
    specs: ["Bluetooth", "240W", "Light show", "Wheels"],
    gradeNotes: "Scuffs from transport, sounds huge.",
    image: "🔊",
  },
  {
    slug: "bose-soundlink-revolve",
    name: "Bose SoundLink Revolve+",
    category: "Sound Systems",
    price: 129,
    originalPrice: 299,
    grade: "A",
    battery: 91,
    warrantyDays: 60,
    seller: "audio-outpost",
    specs: ["360° sound", "Bluetooth", "17hr battery"],
    gradeNotes: "Clean, still holds a full charge.",
    image: "🔊",
  },

  // ─────────────── FRIDGES ───────────────
  {
    slug: "lg-double-door-fridge",
    name: "LG Double-Door Fridge 260L",
    category: "Fridges",
    price: 389,
    originalPrice: 749,
    grade: "B",
    battery: null,
    warrantyDays: 120,
    seller: "home-appliance-hub",
    specs: ["260 litres", "Frost-free", "Inverter compressor"],
    gradeNotes: "Minor scratches on the side, cools perfectly.",
    image: "🧊",
  },
  {
    slug: "samsung-bespoke-fridge",
    name: "Samsung Bespoke Fridge 320L",
    category: "Fridges",
    price: 599,
    originalPrice: 1099,
    grade: "A",
    battery: null,
    warrantyDays: 150,
    seller: "home-appliance-hub",
    specs: ["320 litres", "Digital inverter", "Water dispenser"],
    gradeNotes: "Showroom unit, spotless inside and out.",
    image: "🧊",
  },
  {
    slug: "hisense-bar-fridge",
    name: "Hisense Bar Fridge 90L",
    category: "Fridges",
    price: 129,
    originalPrice: 249,
    grade: "B",
    battery: null,
    warrantyDays: 90,
    seller: "home-appliance-hub",
    specs: ["90 litres", "Compact", "Reversible door"],
    gradeNotes: "Small dent on the door, runs quiet and cold.",
    image: "🧊",
  },

  // ─────────────── TABLETS ───────────────
  {
    slug: "ipad-air-5",
    name: "iPad Air (5th gen)",
    category: "Tablets",
    price: 349,
    originalPrice: 599,
    grade: "A",
    battery: 97,
    warrantyDays: 90,
    seller: "certified-refurb",
    specs: ["64GB", "Wi-Fi", "Starlight", "M1 chip"],
    gradeNotes: "Open-box return, film still on the back.",
    image: "📱",
  },
  {
    slug: "samsung-tab-s9",
    name: "Samsung Galaxy Tab S9",
    category: "Tablets",
    price: 449,
    originalPrice: 799,
    grade: "A",
    battery: 94,
    warrantyDays: 90,
    seller: "verified-reseller",
    specs: ["128GB", "S Pen included", "AMOLED"],
    gradeNotes: "Pristine, with S Pen and box.",
    image: "📱",
  },

  // ─────────────── CAMERAS ───────────────
  {
    slug: "sony-a7iii",
    name: "Sony A7 III",
    category: "Cameras",
    price: 1099,
    originalPrice: 1999,
    grade: "B",
    battery: null,
    warrantyDays: 60,
    seller: "camera-collective",
    specs: ["24.2MP", "12,400 shutter count", "Body only"],
    gradeNotes: "Grip shows light brassing. Sensor clean, shutter tested.",
    image: "📷",
  },
  {
    slug: "canon-r6",
    name: "Canon EOS R6",
    category: "Cameras",
    price: 1349,
    originalPrice: 2499,
    grade: "A",
    battery: null,
    warrantyDays: 90,
    seller: "camera-collective",
    specs: ["20.1MP", "8,900 shutter count", "Body only"],
    gradeNotes: "Studio unit, kept in a case between shoots.",
    image: "📷",
  },

  // ─────────────── GAMING ───────────────
  {
    slug: "playstation-5",
    name: "PlayStation 5 (Disc)",
    category: "Gaming",
    price: 379,
    originalPrice: 549,
    grade: "A",
    battery: null,
    warrantyDays: 90,
    seller: "game-exchange",
    specs: ["825GB SSD", "1 DualSense", "Disc edition"],
    gradeNotes: "Adult-owned, low hours, boxed.",
    image: "🎮",
  },
  {
    slug: "nintendo-switch-oled",
    name: "Nintendo Switch OLED",
    category: "Gaming",
    price: 199,
    originalPrice: 349,
    grade: "B",
    battery: null,
    warrantyDays: 60,
    seller: "game-exchange",
    specs: ["White dock", "64GB", "Joy-Cons tested for drift"],
    gradeNotes: "A few scratches on the dock, screen clean.",
    image: "🎮",
  },
  {
    slug: "xbox-series-s",
    name: "Xbox Series S",
    category: "Gaming",
    price: 179,
    originalPrice: 299,
    grade: "B",
    battery: null,
    warrantyDays: 60,
    seller: "game-exchange",
    specs: ["512GB SSD", "1 controller", "All-digital"],
    gradeNotes: "Light dust marks, fully working.",
    image: "🎮",
  },

  // ─────────────── MONITORS ───────────────
  {
    slug: "dell-24-monitor",
    name: "Dell 24″ Monitor (entry)",
    category: "Monitors",
    price: 59,
    originalPrice: 149,
    grade: "C",
    battery: null,
    warrantyDays: 30,
    seller: "budget-bin",
    specs: ["24-inch", "1080p", "IPS", "HDMI + VGA"],
    gradeNotes: "Visible wear on the stand, panel has no dead pixels.",
    image: "🖥️",
  },
  {
    slug: "lg-ultragear-27",
    name: "LG UltraGear 27″ 144Hz",
    category: "Monitors",
    price: 189,
    originalPrice: 379,
    grade: "A",
    battery: null,
    warrantyDays: 90,
    seller: "screen-source",
    specs: ["27-inch", "1440p", "144Hz", "1ms"],
    gradeNotes: "Gaming monitor in great shape, boxed.",
    image: "🖥️",
  },
];
